Web Proke/Areas/AdminPanel/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_Proke.Models;

namespace Web_Proke.Areas.AdminPanel.Controllers
{
   
    public class AdminController : Controller
    {
        private KutuphaneEntitiesCompactDBEntities db = new KutuphaneEntitiesCompactDBEntities();

        // GET: AdminPanel/Admin
        public ActionResult Index()
        {
            return View(db.Admin.ToList());
        }

        // GET: AdminPanel/Admin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admin.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // GET: AdminPanel/Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminPanel/Admin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AdminID,KullaniciAdi,e_posta,Parola,Adi,Soyadi")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                admin.KayitTarihi = DateTime.Now;
                db.Admin.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(admin);
        }

        // GET: AdminPanel/Admin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           Admin admin = db.Admin.Find(id);
            admin.KayitTarihi = DateTime.Now;
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: AdminPanel/Admin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AdminID,KullaniciAdi,e_posta,Parola,Adi,Soyadi")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(admin).State = EntityState.Modified;
                admin.KayitTarihi = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(admin);
        }

        // GET: AdminPanel/Admin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admin.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: AdminPanel/Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Admin admin = db.Admin.Find(id);
            db.Admin.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
      

    }
}

Web Proke/Areas/AdminPanel/Controllers/AdminKonumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_Proke.Models;

namespace Web_Proke.Areas.AdminPanel.Controllers
{
   
    public class AdminKonumController : Controller
    {
        private KutuphaneEntitiesCompactDBEntities db = new KutuphaneEntitiesCompactDBEntities();

        // GET: AdminPanel/AdminKonum
        public ActionResult Index()
        {
            return View(db.Konum.ToList());
        }

        // GET: AdminPanel/AdminKonum/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Konum konum = db.Konum.Find(id);
            if (konum == null)
            {
                return HttpNotFound();
            }
            return View(konum);
        }

        // GET: AdminPanel/AdminKonum/Create
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KonumID,DolapKodu,RafNo,RafSira")] Konum konum)
        {
            if (ModelState.IsValid)
            {
                db.Konum.Add(konum);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(konum);
        }

        // GET: AdminPanel/AdminKonum/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Konum konum = db.Konum.Find(id);
            if (konum == null)
            {
                return HttpNotFound();
            }
            return View(konum);
        }

        // POST: AdminPanel/AdminKonum/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KonumID,DolapKodu,RafNo,RafSira")] Konum konum)
        {
            if (ModelState.IsValid)
            {
                db.Entry(konum).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(konum);
        }

        // GET: AdminPanel/AdminKonum/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Konum konum = db.Konum.Find(id);
            if (konum == null)
            {
                return HttpNotFound();
            }
            return View(konum);
        }

        // POST: AdminPanel/AdminKonum/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
           Konum konum = db.Konum.Find(id);
            db.Konum.Remove(konum);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web Proke/Areas/AdminPanel/Controllers/AdminÜyelerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web_Proke.Models;

namespace Web_Proke.Areas.AdminPanel.Controllers
{
   
    public class AdminÜyelerController : Controller
    {
        private KutuphaneEntitiesCompactDBEntities db = new KutuphaneEntitiesCompactDBEntities();

        // GET: AdminPanel/AdminÜyeler
        public ActionResult Index()
        {
            return View(db.Üyeler.ToList());
        }

        // GET: AdminPanel/AdminÜyeler/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Üyeler üyeler = db.Üyeler.Find(id);
            if (üyeler == null)
            {
                return HttpNotFound();
            }
            return View(üyeler);
        }

        // GET: AdminPanel/AdminÜyeler/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminPanel/AdminÜyeler/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ÜyeID,ÜyeAdiSoyadi,TelefonNo,a_mail,KullanıcıAdi,Parola,ParolaTekrar")] Üyeler üyeler)
        {
            if (ModelState.IsValid)
            {
                üyeler.KayitTarihi = DateTime.Now;
                db.Üyeler.Add(üyeler);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(üyeler);
        }

        // GET: AdminPanel/AdminÜyeler/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Üyeler üyeler = db.Üyeler.Find(id);
            üyeler.KayitTarihi = DateTime.Now;
            if (üyeler == null)
            {
                return HttpNotFound();
            }
            return View(üyeler);
        }

        // POST: AdminPanel/AdminÜyeler/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ÜyeID,ÜyeAdiSoyadi,TelefonNo,a_mail,KullanıcıAdi,Parola,ParolaTekrar")] Üyeler üyeler)
        {
            if (ModelState.IsValid)
            {
                db.Entry(üyeler).State = EntityState.Modified;
                üyeler.KayitTarihi = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(üyeler);
        }

        // GET: AdminPanel/AdminÜyeler/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Üyeler üyeler = db.Üyeler.Find(id);
            if (üyeler == null)
            {
                return HttpNotFound();
            }
            return View(üyeler);
        }

        // POST: AdminPanel/AdminÜyeler/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Üyeler üyeler = db.Üyeler.Find(id);
            db.Üyeler.Remove(üyeler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web Proke/Areas/AdminPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Admin Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Areas/AdminPanel/Content/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Areas/AdminPanel/Content/sb-admin.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="~/Areas/AdminPanel/Content/plugings/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/Areas/AdminPanel/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">


</head>
<body>

    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">


                <li id="adminuye">@Html.Partial("_LoginPartial")</li>
                
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">


                    <li>
                        @Html.ActionLink("Admin Ekle", "Create", "Admin")
                    </li>
                    <li>
                        @Html.ActionLink("Yayın Ekle", "Create", "AdminKatalog")
                    </li>
                    <li>
                        @Html.ActionLink("Duyuru Ekle", "Create", "AdminDuyurular")
                    </li>
                    <li>
                        @Html.ActionLink("Üye Ekle", "Create", "AdminÜyeler")
                    </li>

                    <li>
                        @Html.ActionLink("Çalışan Ekle", "Create", "AdminCalisanlar")
                    </li>
                    <li>
                        @Html.ActionLink("Konum Ekle", "Create", "AdminKonum")
                    </li>

                    <li>
                        @Html.ActionLink("Adminleri Görüntüle", "Index", "Admin")
                    </li>
                    <li>
                        @Html.ActionLink("Yayınları Görüntüle", "Index", "AdminKatalog")
                    </li>
                  
                    <li>
                        @Html.ActionLink("Üyeleri Görüntüle", "Index", "AdminÜyeler")
                    </li>

                    <li>
                        @Html.ActionLink("Çalışanları Görüntüle", "Index", "AdminCalisanlar")
                    </li>
                  


                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
       




        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->

    @RenderBody()
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/Areas/AdminPanel/Scripts/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Areas/AdminPanel/Scripts/bootstrap.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="~/Areas/AdminPanel/Scripts/plugins/morris/raphael.min.js"></script>
    <script src="~/Areas/AdminPanel/Scripts/plugins/morris/morris.min.js"></script>
    <script src="~/Areas/AdminPanel/Scripts/plugins/morris/morris-data.js"></script>
</body>
</html>